import { NextResponse } from 'next/server'
import { createClient } from '@supabase/supabase-js'
import JSZip from 'jszip'

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL
const supabaseKey = process.env.SUPABASE_SERVICE_ROLE_KEY

if (!supabaseUrl || !supabaseKey) {
  throw new Error('Missing Supabase credentials')
}

const supabase = createClient(supabaseUrl, supabaseKey)

export async function POST(request: Request) {
  try {
    const { resultId } = await request.json()

    if (!resultId) {
      return NextResponse.json({ error: 'Missing resultId' }, { status: 400 })
    }

    console.log('[Package] Creating video package for result:', resultId)

    // Fetch result data
    const { data: result, error: dbError } = await supabase
      .from('results')
      .select('*')
      .eq('id', resultId)
      .single()

    if (dbError || !result) {
      return NextResponse.json({ error: 'Result not found' }, { status: 404 })
    }

    // Create ZIP package
    const zip = new JSZip()

    // Add project data as JSON
    zip.file('project.json', JSON.stringify({
      scenes: result.scenes || [],
      script: result.script || {},
      seo: result.seo || {},
      capcut_steps: result.capcut_steps || [],
      thumbnail: result.thumbnail || {}
    }, null, 2))

    // Add README
    zip.file('README.md', `# Video Project: ${result.seo?.title || 'Untitled'}

## Contents
- project.json: Complete video data with scenes, script, and metadata
- render.py: Python script to render video (requires MoviePy)
- requirements.txt: Python dependencies

## Quick Start
1. Install dependencies: \`pip install -r requirements.txt\`
2. Run: \`python render.py\`
3. Output: final_video.mp4

## Scene Overview
${result.scenes?.map((s: any) => `- Scene ${s.id}: ${s.title} (${s.start_time} - ${s.end_time})`).join('\n') || 'No scenes'}

## SEO
- Title: ${result.seo?.title || 'N/A'}
- Tags: ${result.seo?.tags?.join(', ') || 'N/A'}
`)

    // Add Python render script
    zip.file('render.py', `#!/usr/bin/env python3
"""
Video Rendering Script
Generated by YouTube AI Builder
"""

import json
from moviepy.editor import *
from PIL import Image, ImageDraw, ImageFont
import os

# Config
OUTPUT_FILE = "final_video.mp4"
VIDEO_SIZE = (1080, 1920)  # Vertical (TikTok/Reels)
FPS = 24

# Load project data
with open("project.json", "r") as f:
    data = json.load(f)

scenes = data["scenes"]
script = data["script"]

def create_text_clip(text, duration):
    return TextClip(
        text,
        fontsize=60,
        color='white',
        font="Arial-Bold",
        size=(900, None),
        method='caption'
    ).set_position(("center", "bottom")).set_duration(duration)

def create_placeholder_image(scene_id, text, width=1080, height=1920):
    img = Image.new('RGB', (width, height), color=(30, 30, 40))
    draw = ImageDraw.Draw(img)
    
    try:
        font = ImageFont.truetype("Arial.ttf", 80)
    except:
        font = ImageFont.load_default()
    
    draw.text((width/2, height/2), f"Scene {scene_id}\\n{text[:50]}", 
              fill=(255, 255, 255), anchor="mm", font=font)
    
    filename = f"scene_{scene_id}.jpg"
    img.save(filename)
    return filename

# Build video
video_clips = []

for scene in scenes:
    start_time = scene["start_time"].split(":")
    end_time = scene["end_time"].split(":")
    
    start_sec = int(start_time[0]) * 60 + int(start_time[1])
    end_sec = int(end_time[0]) * 60 + int(end_time[1])
    duration = max(1, end_sec - start_sec)
    
    # Create placeholder image
    img_path = create_placeholder_image(
        scene["id"], 
        scene.get("visual_description", scene.get("title", ""))
    )
    
    img_clip = ImageClip(img_path).resize(height=VIDEO_SIZE[1]).set_position("center").set_duration(duration)
    
    # Add text overlay
    text = scene.get("on_screen_text", "")
    if text:
        text_clip = create_text_clip(text, duration)
        scene_clip = CompositeVideoClip([img_clip, text_clip], size=VIDEO_SIZE)
    else:
        scene_clip = img_clip
    
    video_clips.append(scene_clip)

# Combine
print(f"Combining {len(video_clips)} scenes...")
final_video = concatenate_videoclips(video_clips, method="compose")

# Export
print(f"Rendering video to {OUTPUT_FILE}...")
final_video.write_videofile(
    OUTPUT_FILE,
    fps=FPS,
    codec="libx264",
    audio_codec="aac"
)

print(f"✅ Video complete: {OUTPUT_FILE}")
`)

    // Add requirements.txt
    zip.file('requirements.txt', `moviepy==1.0.3
Pillow==10.0.0
numpy==1.24.3
`)

    // Generate ZIP
    const zipBuffer = await zip.generateAsync({ type: 'nodebuffer' })

    // Return ZIP file
    return new NextResponse(zipBuffer, {
      headers: {
        'Content-Type': 'application/zip',
        'Content-Disposition': `attachment; filename="video-project-${resultId}.zip"`,
      },
    })
  } catch (error) {
    console.error('[Package] Error:', error)
    return NextResponse.json(
      { error: error instanceof Error ? error.message : 'Failed to create package' },
      { status: 500 }
    )
  }
}
